name: Django
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"

jobs:
  pytest:
    name: Test Django
    timeout-minutes: 5
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: blog_demo_django_app
          POSTGRES_PASSWORD: security_is_important
          POSTGRES_DB: blog_demo_django_app
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Set up Python 3.9.4
        uses: actions/setup-python@v3
        with:
          python-version: 3.9.4
      - name: Cache Pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('requirements.txt', 'requirements-test.txt') }}
      - name: Setup
        run: |
          pip install --requirement requirements.txt --requirement requirements-test.txt
      - name: Run Tests
        run: pytest
        env:
          DATABASE_URL: postgres://blog_demo_django_app:security_is_important@localhost/blog_demo_django_app

  check-django-configuration:
    name: Check Django Configuration
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Set up Python 3.9.4
        uses: actions/setup-python@v3
        with:
          python-version: 3.9.4
      - name: Cache Pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('requirements.txt') }}
      - name: Setup
        run: |
          pip install --requirement requirements.txt
      - name: Test Django configured correctly
        run: |
          python manage.py makemigrations --check
          python manage.py check --deploy --fail-level INFO
        env:
          DATABASE_URL: sqlite:///db.sqlite3
          SECRET_KEY: Some very long and complex string which is very, very secure.
          CANONICAL_HOST: somecanonicalhost.com
